---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.40
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: pretty-format-json
        args: ["--no-sort-keys"]
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: no-commit-to-branch
        args: [--branch, staging]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.11.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        additional_dependencies: [types-all]
        exclude: ^testing/resources/
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: autopep8
        name: autopep8
        entry: autopep8
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
